import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AntdRegistry>
        <div className="w-full flex place-content-center items-center">
        <div className="w-[1280px] h-[64px]  flex items-center text-xl font-bold text-primary">Uygun Sistem</div>

        </div>
        <div className="flex place-content-center w-full min-h-screen bg-secondary">
          <div className="w-[1280px] my-4 rounded-lg bg-w">{children}</div>
        </div></AntdRegistry>
      </body>
    </html>
  );
}
